export const skills = {
  languages: [
    { name: "End-to-End Recruitment", level: 92 },
    { name: "Candidate Sourcing", level: 90 },
    { name: "Resume Screening", level: 88 },
    { name: "Telephonic Interviews", level: 86 },
    { name: "Interview Coordination", level: 90 },
    { name: "Job Description Writing", level: 85 },
  ],
  frontend: [
    { name: "Onboarding Documentation", level: 88 },
    { name: "Offer Letter Preparation", level: 84 },
    { name: "Employee Records", level: 86 },
    { name: "Attendance & Leave Tracking", level: 82 },
    { name: "Internal HR Communication", level: 84 },
    { name: "Employee Engagement", level: 86 },
  ],
  backend: [
    { name: "Naukri.com", level: 88 },
    { name: "LinkedIn Recruiter", level: 86 },
    { name: "Indeed", level: 84 },
    { name: "Internshala", level: 82 },
    { name: "HR One ATS", level: 84 },
    { name: "SAP / HRIS", level: 76 },
  ],
  databases: [
    { name: "Recruitment Reporting", level: 86 },
    { name: "Pipeline Management", level: 88 },
    { name: "TAT Tracking", level: 82 },
    { name: "Offer Acceptance Metrics", level: 80 },
    { name: "MS Excel / Sheets", level: 84 },
  ],
  devops: [
    { name: "Professional Communication", level: 92 },
    { name: "Stakeholder Management", level: 88 },
    { name: "Attention to Detail", level: 90 },
    { name: "Time Management", level: 88 },
    { name: "Candidate Experience", level: 90 },
  ],
};

export const projects = [
  {
    id: "01",
    tag: "Recruitment - IT Roles",
    emoji: "TA",
    title: "Multi-Role IT Hiring Pipeline",
    subtitle: "End-to-end recruitment at Eice Technology",
    desc: "Managed recruitment across simultaneous IT roles, including requirement gathering, sourcing, resume screening, interview coordination, offer roll-out, and daily progress reporting.",
    tech: ["Naukri", "LinkedIn", "Indeed", "Internshala", "Pipeline Tracker"],
    featured: true,
    highlight: "50+ profiles/week",
  },
  {
    id: "02",
    tag: "Candidate Experience",
    emoji: "CX",
    title: "Structured Candidate Communication",
    subtitle: "Professional hiring journey management",
    desc: "Coordinated candidate and hiring-manager communication through email, phone, and WhatsApp while keeping feedback cycles timely and reducing scheduling conflicts.",
    tech: ["Interview Scheduling", "Email", "Phone", "WhatsApp", "Feedback Tracking"],
    featured: true,
    highlight: "Zero scheduling conflicts",
  },
  {
    id: "03",
    tag: "HR Operations",
    emoji: "OP",
    title: "New Hire Onboarding Flow",
    subtitle: "Documentation, access setup, and induction",
    desc: "Prepared offer letters, supported system access setup, maintained employee records, and conducted structured induction sessions for new hires.",
    tech: ["Offer Letters", "Employee Records", "HR One", "Induction", "Documentation"],
    featured: false,
    highlight: "End-to-end onboarding",
  },
  {
    id: "04",
    tag: "Engagement",
    emoji: "EE",
    title: "Employee Engagement Initiatives",
    subtitle: "Workplace culture and team morale",
    desc: "Planned and executed employee engagement activities including Fun Fridays, team outings, and annual events to improve morale and workplace connection.",
    tech: ["Event Planning", "Internal Communication", "Canva", "Coordination"],
    featured: false,
    highlight: "Culture building",
  },
  {
    id: "05",
    tag: "Research",
    emoji: "RS",
    title: "Telecom Sector Research Report",
    subtitle: "Academic market analysis project",
    desc: "Authored a research report on the Indian telecommunications sector, covering market trends, competitive landscape, key players, and growth drivers.",
    tech: ["Research", "Market Analysis", "MS Office", "Presentation"],
    featured: false,
    highlight: "Academic project",
  },
];

export const experience = [
  {
    company: "Eice Technology Pvt. Ltd.",
    role: "HR Recruiter",
    period: "March 2026 - Present",
    live: true,
    desc: "Managing end-to-end recruitment for IT roles, from requirement gathering and candidate sourcing to screening, interview coordination, offer roll-out, and recruitment reporting.",
    achievements: [
      "Sourced and screened 50+ candidates per week across Naukri, LinkedIn, Indeed, and Internshala",
      "Drafted clear job descriptions and postings for multiple IT positions",
      "Coordinated interviews between candidates and hiring managers with timely feedback follow-up",
      "Maintained live candidate pipeline trackers and daily recruitment progress reports",
      "Delivered prompt candidate communication through email, phone, and WhatsApp",
    ],
    tags: ["Recruitment", "Naukri", "LinkedIn", "Interview Coordination", "Reporting"],
  },
  {
    company: "Eglogics Softech Pvt. Ltd.",
    role: "HR Executive",
    period: "April 2023 - August 2023",
    live: false,
    desc: "Handled full-cycle recruitment and HR operations for an IT services firm, including job posting, sourcing, screening, onboarding, employee records, and engagement initiatives.",
    achievements: [
      "Executed recruitment from JD drafting and portal sourcing to interviews and offer letters",
      "Maintained HR One ATS database and candidate records with high accuracy",
      "Tracked recruitment metrics including TAT, offer acceptance rate, and pipeline status",
      "Managed employee records, attendance, leave tracking, and HR communications",
      "Planned Fun Fridays, team outings, and annual employee engagement events",
    ],
    tags: ["HR One", "Onboarding", "Employee Records", "Engagement", "HR Operations"],
  },
  {
    company: "Tech Mahindra",
    role: "Customer Support Associate",
    period: "March 2022 - June 2022",
    live: false,
    desc: "Provided email-based customer support for the AEML process while maintaining service quality and SLA timelines.",
    achievements: [
      "Resolved customer queries accurately within defined SLA timelines",
      "Maintained professional and empathetic written communication",
      "Supported positive customer satisfaction through consistent service quality",
    ],
    tags: ["Email Support", "AEML", "SLA", "Written Communication"],
  },
];

export const stats = [
  { value: "1+", label: "Year HR Experience", icon: "HR" },
  { value: "50+", label: "Profiles Screened Weekly", icon: "TA" },
  { value: "3", label: "Recruitment Portals", icon: "ATS" },
  { value: "MBA", label: "Human Resources", icon: "ED" },
];

export const services = [
  {
    icon: "TA",
    title: "Recruitment Support",
    desc: "End-to-end hiring support across requirement gathering, sourcing, screening, interview coordination, and offer follow-up.",
    tags: ["Sourcing", "Screening", "Coordination", "Offers"],
  },
  {
    icon: "JD",
    title: "Job Posting & JD Writing",
    desc: "Clear job descriptions and role postings designed to improve applicant quality and reduce irrelevant applications.",
    tags: ["JD Writing", "Naukri", "LinkedIn", "Indeed"],
  },
  {
    icon: "ATS",
    title: "ATS & Pipeline Tracking",
    desc: "Candidate database maintenance, pipeline tracking, recruitment reports, and metric updates for better hiring visibility.",
    tags: ["HR One", "Reports", "TAT", "Pipeline"],
  },
  {
    icon: "ON",
    title: "Onboarding Documentation",
    desc: "Offer letters, joining documentation, employee record updates, and induction coordination for new hires.",
    tags: ["Offer Letters", "Records", "Induction", "HRIS"],
  },
  {
    icon: "EE",
    title: "Employee Engagement",
    desc: "Support for employee engagement activities, internal communication, and workplace culture initiatives.",
    tags: ["Events", "Communication", "Canva", "Culture"],
  },
  {
    icon: "CX",
    title: "Candidate Experience",
    desc: "Prompt, professional communication with candidates and stakeholders across hiring stages.",
    tags: ["Email", "Phone", "WhatsApp", "Feedback"],
  },
];
