export const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://nehahr.online";

export const site = {
  name: "Neha Singh",
  shortTitle: "Neha HR",
  title: "Neha Singh - HR Executive, HR Operations & Talent Acquisition in Noida",
  description:
    "Portfolio of Neha Singh, an HR Executive and MBA Human Resources graduate in Ghaziabad/Noida specializing in talent acquisition, HR operations, IT recruitment, candidate sourcing, resume screening, onboarding, ATS tracking, and employee engagement.",
  url: siteUrl,
  email: "ns291999@gmail.com",
  linkedin: "https://linkedin.com/in/nehas29",
  resume: "https://drive.google.com/drive/folders/1bqN9C5PKELTy953VnaIZ-5zRAMlR-EUX",
  locale: "en_IN",
  location: "Ghaziabad, Uttar Pradesh, India",
  region: "Noida / Ghaziabad",
  role: "HR Executive",
  currentCompany: "Eice Technology Pvt. Ltd.",
  ogImage: "/opengraph-image",
};

export const seoKeywords = [
  "Neha Singh",
  "Neha Singh HR",
  "Neha HR portfolio",
  "Neha Singh portfolio",
  "Neha Singh resume",
  "Neha Singh CV",
  "Neha Singh HR Executive",
  "Neha Singh HR Operations",
  "Neha Singh Talent Acquisition",
  "Neha Singh HR Recruiter",
  "HR Executive",
  "HR Recruiter Noida",
  "HR Recruiter Ghaziabad",
  "HR Recruiter Delhi NCR",
  "HR Executive Noida",
  "HR Executive Ghaziabad",
  "HR Executive Delhi NCR",
  "HR Operations Noida",
  "HR Operations Ghaziabad",
  "HR Operations Delhi NCR",
  "Talent Acquisition Noida",
  "Talent Acquisition Ghaziabad",
  "Talent Acquisition Delhi NCR",
  "Talent Acquisition Specialist Noida",
  "Talent Acquisition Specialist Ghaziabad",
  "Talent Acquisition Specialist Delhi NCR",
  "IT Recruiter Noida",
  "IT Recruiter Ghaziabad",
  "IT Recruiter Delhi NCR",
  "Recruitment Specialist Noida",
  "Recruitment Specialist Ghaziabad",
  "Recruitment Coordinator",
  "Recruitment Executive",
  "Human Resources Executive",
  "IT Recruitment",
  "Human Resources portfolio",
  "HR portfolio India",
  "MBA Human Resources",
  "Candidate Sourcing",
  "Artificial Intelligence",
  "AI-assisted Recruitment",
  "Resume Screening",
  "Profile Screening",
  "Candidate Screening",
  "Job Posting",
  "Job Description Writing",
  "Interview Coordination",
  "Offer Letter Preparation",
  "Employee Onboarding",
  "HR Operations",
  "ATS Management",
  "HR One ATS",
  "Naukri Recruiter",
  "LinkedIn Recruiter",
  "Indeed Sourcing",
  "Internshala Hiring",
  "Recruitment Reporting",
  "Employee Engagement",
];
